spring.application.name=Coldwatefish-project


server.port=8090




spring.datasource.url=jdbc:mariadb://coldwaterfish.ctyike4yosu5.ap-northeast-2.rds.amazonaws.com:3306/coldwaterfish?useSSL=false&characterEncoding=UTF-8

spring.datasource.username=trout_master
spring.datasource.password=secure_pass123!


spring.datasource.driver-class-name=org.mariadb.jdbc.Driver




spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.mail.host=smtp.gmail.com
spring.mail.port=587


spring.mail.username=forestcrab2018@gmail.com

spring.mail.password=jbgaoqcjpjfzxlhi


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# ==========================================
# AWS S3 ??? ?? ?? (?? ??)
# ==========================================

# [?? ?? 1]: ????? ?? ???? ???? ?? ?????.
cloud.aws.credentials.access-key=AKIA3HELV4TCS4F6KK7W
cloud.aws.credentials.secret-key=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   
# [?? ?? 2]: S3 ??? ??? ??(??)?? ?????.
cloud.aws.region.static=ap-northeast-2

# [??]: ??? ??? ??? ??? ?? ?????.
cloud.aws.s3.bucket=cold-fish-storage 

# [??]: ?? ?? ? ???? AWS ?? ??? ???? ??? ????.
cloud.aws.stack.auto=false


spring.mvc.pathmatch.matching-strategy=ant_path_matcher


