server {
    listen 80;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        #  리액트 페이지에서 새로고침했을 때 404 에러가 나는 것을 방지합니다.
        try_files $uri $uri/ /index.html;
    }
}